apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "consumer-chart.fullname" . }}
  labels:
    {{- include "consumer-chart.labels" . | nindent 4 }}
spec:
  {{- with .Values.job }}
  activeDeadlineSeconds: {{ .activeDeadlineSeconds }} 
  backoffLimit: {{ .backoffLimit }}
  completions: {{ .completions }}
  parallelism: {{ .parallelism }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "consumer-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "consumer-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.podSpec.restartPolicy }}
      containers:
        - name: {{ include "consumer-chart.name" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "consumer-chart.name" . }}
            - secretRef:
                name: {{ .Values.dataSource.credentialsSecret }}
          env:
            - name: DATA_SOURCE_CA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dataSource.clientCertSecret }}
                  key: ca.crt
                  optional: false
            - name: DATA_SOURCE_CRT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dataSource.clientCertSecret }}
                  key: tls.crt
                  optional: false
            - name: DATA_SOURCE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dataSource.clientCertSecret }}
                  key: tls.key
                  optional: false
            - name: MESSAGE_QUEUE_CA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageQueue.brokerCertSecret }}
                  key: ca.crt
                  optional: false
            - name: MESSAGE_QUEUE_CRT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageQueue.clientCertSecret }}
                  key: user.crt
                  optional: false
            - name: MESSAGE_QUEUE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageQueue.clientCertSecret }}
                  key: user.key
                  optional: false
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
