apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "consumer-chart.name" . }}-ca
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
spec:
  isCA: true
  commonName: identity.swish-analytics-test.consumer.swishkube.lan
  secretName: {{ .Values.cert.caSecret }}
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 8760h # 12 months
  renewBefore: 6570h # 9 months
  issuerRef:
    name: swishkube-root-ca
    kind: ClusterIssuer
    group: cert-manager.io